apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      environment: green
  template:
    metadata:
      labels:
        app: myapp
        environment: green
    spec:
      containers:
      - name: myapp
        image: jemesbond/angular:v2
  strategy:
    blueGreen:
      activeService: myapp-green
      previewService: myapp-blue
      autoPromotionSeconds: 60
